version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    working_directory: ~/project/magnolia-thymeleaf-renderer

    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      # dependency:go-offline doesn't support multi-module reactors
      - run: mvn install:install-file -Dpackaging=pom -Dfile=magnolia-thymeleaf-renderer-module/pom.xml -DpomFile=magnolia-thymeleaf-renderer-module/pom.xml
      - run: mvn --fail-never dependency:go-offline || true
      - run: mvn dependency:purge-local-repository -DmanualInclude="org.sevensource.magnolia:magnolia-thymeleaf-renderer-module"


      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdir cd
              openssl aes-256-cbc -a -A -d -md sha256 -k "${GPG_SIGNING_SECRET}" -out cd/codesigning.asc <<<${GPG_SIGNING_DATA}
              gpg --batch --fast-import cd/codesigning.asc
              echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
              echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
              mvn -s ../.circleci/settings.xml -DskipTests package deploy
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only:
                - master
                - develop
